services:
  app:
    container_name: app
    build: app
    image: physproj-home-app
    restart: always
    volumes:
      - /opt/physproj/app/data:/app/data
  admin-api:
    container_name: admin-api
    build: admin-api
    image: physproj-home-admin-api
    restart: always
    ports:
      - "7188:7188"
    volumes:
      - /opt/physproj/admin-api/data:/app/data
      - /mnt/publications:/app/files:ro
  admin-web:
    container_name: admin-web
    build: admin-web
    image: physproj-home-admin-web
    restart: always
    ports:
      - "7189:80"
    volumes:
      - /opt/physproj/admin-web/nginx:/var/log/nginx