services:
  app:
    container_name: worker-app
    build: worker-app
    image: physproj-worker-app
    restart: always
    volumes:
      - /opt/physproj/worker-app/data:/app/data
  admin-api:
    container_name: admin-api
    build: admin-api
    image: physproj-admin-api
    restart: always
    ports:
      - "7188:7188"
    volumes:
      - /opt/physproj/admin-api/data:/app/data
  admin-web:
    container_name: admin-web
    build: admin-web
    image: physproj-admin-web
    restart: always
    ports:
      - "7189:7189"
    volumes:
      - /opt/physproj/admin-web/nginx:/var/log/nginx
  site-api:
    container_name: site-api
    build: site-api
    image: physproj-site-api
    restart: always
    ports:
      - "7288:7288"
    volumes:
      - /opt/physproj/site-api/data:/app/data
  site-web:
    container_name: site-web
    build: site-web
    image: physproj-site-web
    restart: always
    ports:
      - "7289:7289"
    volumes:
      - /opt/physproj/site-web/nginx:/var/log/nginx