services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker/registry/data:/var/lib/registry