services:
  app:
    container_name: app
    build: worker-app
    image: physproj-home-app
    restart: always
    volumes:
      - /opt/physproj/app/data:/app/data
      - /mnt/publications:/app/files:ro
  admin-api:
    container_name: admin-api
    build: admin-api
    image: physproj-home-admin-api
    restart: always
    ports:
      - "7188:7188"
    volumes:
      - /opt/physproj/admin-api/data:/app/data
      - /mnt/publications:/app/files:ro
  admin-web:
    container_name: admin-web
    build: admin-web
    image: physproj-home-admin-web
    restart: always
    ports:
      - "7189:80"
    volumes:
      - /opt/physproj/admin-web/nginx:/var/log/nginx
  site-api:
    container_name: site-api
    build: site-api
    image: physproj-home-site-api
    restart: always
    ports:
      - "7288:7288"
    volumes:
      - /opt/physproj/site-api/data:/app/data
  site-web:
    container_name: site-web
    build: site-web
    image: physproj-home-site-web
    restart: always
    ports:
      - "7289:80"
    volumes:
      - /opt/physproj/site-web/nginx:/var/log/nginx