services:
  rabbitmq:
    container_name: physproj-rabbitmq
    restart: always
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /opt/physproj/rabbitmq/data:/var/lib/rabbitmq/
      - /opt/physproj/rabbitmq/logs:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: #{RABBITMQ_USER}#
      RABBITMQ_DEFAULT_PASS: #{RABBITMQ_PASSWORD}#
  meilisearch:
    container_name: physproj-meilisearch
    image: getmeili/meilisearch:v1.4
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - /opt/physproj/meilisearch/data:/meili_data
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: #{MEILI_MASTER_KEY}#