services:
  mongo:
    container_name: physproj-mongo
    image: mongo:4.4.18
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  postgres:
    container_name: physproj-postgres
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
  rabbitmq:
    container_name: physproj-rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
volumes:
  mongo:
  postgres:
  rabbitmq: