services:
  mongo:
    container_name: physproj-mongo
    restart: always
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    volumes:
      - /opt/physproj/mongo/data:/data/db
  postgres:
    container_name: physproj-postgres
    restart: always
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - /opt/physproj/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
  rabbitmq:
    container_name: physproj-rabbitmq
    restart: always
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /opt/physproj/rabbitmq/data:/var/lib/rabbitmq/
  meilisearch:
    container_name: physproj-meilisearch
    image: getmeili/meilisearch:v1.4
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - /opt/physproj/meilisearch/data:/meili_data
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: 123456