name: deploy-admin-web

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SRV_HOST : ${{vars.SRV_GATEWAY_HOST}}
            SRV_USER : ${{vars.SRV_GATEWAY_USER}}
        strategy:
            matrix:
                node-version: [18.x]
        steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: "./src/PhysProj/Phys.Lib.Admin.Web/package-lock.json"
        - name: NPM install
          run: npm install
          working-directory: ./src/PhysProj/Phys.Lib.Admin.Web
        - name: NPM Build
          run: npm run build
          working-directory: ./src/PhysProj/Phys.Lib.Admin.Web
        - name: Copy build to docker build directory
          run: cp -r ./build $GITHUB_WORKSPACE/cicd/envs/public/srv-app/admin-web
          working-directory: ./src/PhysProj/Phys.Lib.Admin.Web
        - name: Init SSH agent
          run: |
            echo "${{ secrets.SRV_GATEWAY_SSH_PRIVATE_KEY }}" > ssh_key
            chmod 600 ssh_key
            eval `ssh-agent`
            ssh-add ssh_key
            ssh-keyscan $SRV_HOST >> /root/.ssh/known_hosts
#            ssh -o StrictHostKeyChecking=no $SRV_USER@$SRV_HOST
        - name: Create docker context
          run: docker context create srv-gateway --docker "host=ssh://$SRV_USER@$SRV_HOST"
        - name: Build and deploy docker image
          run: bash ./admin-web/deploy.sh
          working-directory: ${{ github.workspace }}/cicd/envs/public/srv-app/