name: deploy-admin-web

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src/PhysProj/Phys.Lib.Admin.Web
        env:
            SRV_HOST : ${{vars.SRV_GATEWAY_HOST}}
            SRV_USER : ${{vars.SRV_GATEWAY_USER}}
#        strategy:
#            matrix:
#                node-version: [18.x]
        steps:
        - name: Create docker context
          run: docker context create $SRV_USER --docker "host=ssh://$SRV_USER@$SRV_HOST"