name: deploy-admin-api

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app-dotnet.yml
    with:
      project-src-name: Phys.Lib.Admin.Api
      project-ci-name: admin-api
    secrets: inherit