name: deploy-admin-web

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app-web.yml
    with:
      project-src-name: Phys.Lib.Admin.Web
      project-ci-name: admin-web
    secrets: inherit