name: deploy-app-dotnet

on:
  workflow_call:
    inputs:
      project-src-name:
        required: true
        type: string
      project-ci-name:
        required: true
        type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SRV_HOST : ${{vars.SRV_GATEWAY_HOST}}
            SRV_USER : ${{vars.SRV_GATEWAY_USER}}
            SSH_PATH: /home/runner/.ssh
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            SRC_PATH: ./src/PhysProj/${{inputs.project-src-name}}
            CI_APP_NAME: ${{inputs.project-ci-name}}
        strategy:
            matrix:
              dotnet-version: [ '8.x.x' ]
        steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Update appsettings.json
          uses: cschleiden/replace-tokens@v1
          with:
            files: '${{ github.workspace }}/cicd/envs/public/srv-app/${{ env.CI_APP_NAME }}/settings/appsettings.json'
          env:
            MONGO: ${{ secrets.SRV_MONGO_URL }}
            RABBIT: ${{ secrets.SRV_RABBIT_URL }}
            MEILI_URL: ${{ secrets.SRV_MEILI_URL }}
            MEILI_KEY: ${{ secrets.SRV_MEILI_KEY }}
        - name: Show appsettings.json
          run: |
            appsettingsJson="$(cat $GITHUB_WORKSPACE/cicd/envs/public/srv-app/$CI_APP_NAME/settings/appsettings.json)"
            echo $appsettingsJson
        - name: Setup dotnet ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Dotnet app build
          run: |
            version=`date -u +%Y.%m.%d.%H%M`
            dotnet publish --output $GITHUB_WORKSPACE/cicd/envs/public/srv-app/$CI_APP_NAME/bin /p:Version=$version
          working-directory: ${{ env.SRC_PATH }}
        - name: Init SSH agent
          run: |
            mkdir -p $SSH_PATH
            ssh-keyscan $SRV_HOST >> $SSH_PATH/known_hosts
            echo "${{ secrets.SRV_GATEWAY_SSH_PRIVATE_KEY }}" > $SSH_PATH/ssh_key
            chmod 600 $SSH_PATH/ssh_key
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add $SSH_PATH/ssh_key
        - name: Build and deploy docker image
          run: | 
            docker context create remote --docker "host=ssh://$SRV_USER@$SRV_HOST"
            docker --context remote compose --file docker-compose.yml --project-name physproj up --detach --build --force-recreate $CI_APP_NAME
          working-directory: ${{ github.workspace }}/cicd/envs/public/srv-app/