name: ssh-login-test
on: workflow_dispatch
jobs:
  ssh-login:
    runs-on: ubuntu-latest
    steps:
    - name: test
      env:
        SSH_KEY : ${{secrets.SRV_GATEWAY_SSH_PRIVATE_KEY}}
        SRV_HOST : ${{vars.SRV_GATEWAY_HOST}}
        SRV_USER : ${{vars.SRV_GATEWAY_USER}}
      run: |
        echo $SSH_KEY >> ssh_key
        ssh-agent
        ssh-add ssh_key
        ssh $SRV_USER@SRV_HOST
